qsub -P RDS-CORE-SIH4HPC-RW -N gs_3 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=2 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_3 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=3 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_4 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=4 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_5 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=5 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_6 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=6 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_7 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=7 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_8 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=8 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_9 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=9 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_10 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=10 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_11 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=11 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_12 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=12 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_13 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=13 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_14 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=14 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_15 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=15 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_16 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=16 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_17 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=17 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_18 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=18 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_19 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=19 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_20 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=20 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_21 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=21 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_22 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=22 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_23 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=23 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_24 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=24 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_25 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=25 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_26 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=26 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_27 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=27 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_28 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=28 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_29 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=29 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh
qsub -P RDS-CORE-SIH4HPC-RW -N gs_30 -l walltime=24:0:0 -l select=1:ncpus=2:mem=23gb -v NTOPICS=30 /home/dvanichkina/scratch_sih/obesity/gensim_model_testing.sh