byline_replacementlist = [
    "Exclusive ",
 " And ",
  # jobs
 "National",
 "Correspondent",
 "Political",
 "Health " ,
 "Political",
 "Education" ,
 "Commentator",
 "Regional",
 "Agencies",
 "Defence",
 "Fashion",
 "Music",
 "Social Issues",
 "Reporter",
 "Chief",
 "Business",
 "Workplace",
 "Editor",
 "Indulge",
 "Science",
 "Sunday",
 "Saturdays",
 "Writer",
 "Food ",
 "Dr ",
 "Professor ",

 # cities,
 "Las Vegas",
 "Melbourne",
 "Canberra",
 "Brisbane",
 "Sydney",
 "Perth",
 "Adelaide",
 "Chicago",
 "Daily Mail, London" ,
 "London Correspondent",
 "London Daily Mail",
 "Buenos Aires" ,
 "New York",
 "New Delhi",
 "London",
 ", Washington",
 "Beijing",
 "Health",
 # random stuff
 "State ",
 "Council On The Ageing",
 "Words ",
 "Text",
 "By ",
 "With ",
 " In ",
 " - ",
 ":",
 "Proprietor Realise Personal Training Company",
 "B+S Nutritionist",
 "My Week",
 "Medical",
 "Manufacturing",
 "Brought To You",
 "Film ",
 "Reviews ",
 "Comment",
 "Personal",
 "Finance",
 "Natural ",
 "Solutions ",
 "Special ",
 "Report ",
 "Recipe ",
 "Photography ",
 "Photo",
 "-At-Large",
 "Styling ",
 "Preparation ",
 # individual,
 " - Ian Rose Is A Melbourne Writer." ,
 "Cycling Promotion Fund Policy Adviser ",
 ". Dannielle Miller Is The Head Of Enlighten Education. Enlighten Works With Teenage Girls In High Schools On Developing A Positive Self-Esteem And Healthy Body Image." ]